# ====site info 站点信息====
# 标题
title: Gallery - JEKYLL

# ====config 设置====
# 链接形式
permalink: /:year/:month/:day/:title.html

# 根目录设置
# 如果是根目录, 不要填写'/', 直接留空就行
# 如果是非根目录访问, 如http://abc.com/blog, 此处填写'/blog'
baseurl: /jekyll-theme-gallery

# 分页设置
paginate: 10

# 分页形式
paginate_path: "page:num"

# markdown语法
markdown: kramdown

# 时区
timezone: Asia/Shanghai

# 依赖组件
plugins: [jekyll-paginate]

# 本地服务器 
host: 0.0.0.0
port: 4001










